"""
uncertainty.py — v2 (EPFL-grade empirical residual prediction intervals)

Method
------
For each (saison, type_jour, heure_hce) cell, compute empirical residual
quantiles from EPEX history:

    residual = epex_price - cell_mean
    q10_res, q90_res = empirical 10/90 percentiles of residuals (€/MWh)

At prediction time:

    p10(t) = pfc.price_shape(t) + q10_res[cell(t)]
    p90(t) = pfc.price_shape(t) + q90_res[cell(t)]

Both quantiles are **additive in €/MWh** (q10_res ≤ 0, q90_res ≥ 0 in
expectation), not multiplicative ratios. This handles negative prices
correctly (since Phase 5) and removes dependence on cell_mean magnitude
that made the v1 method unstable near zero.

No horizon widening factor: the PFC is anchored on EEX forwards at all
delivery periods via arbitrage-free calibration (`ArbitrageFreeCalibrator`),
so residual variance does not grow with horizon in any theoretically-
justified way for an anchored model. Empirical evidence from Phase 10 SC#1
scorecard (commit 9418e3a) showed the v1 HORIZON_WIDENING ×1.5–4.2 inflated
the IC80 bandwidth to ~10× the empirical residual q10–q90 width, producing
observed IC80 coverage of 99% (vs nominal 80%).

Validation
----------
On the calibration set, observed_p = nominal 20% by construction (empirical
quantile property — see `test_uncertainty_in_sample_coverage_nominal`).
On out-of-sample data, deviations measure genuine model miscalibration.

References
----------
- Christoffersen 1998, "Evaluating Interval Forecasts" — coverage tests
- KYOS / Volue HPFC documentation — empirical residual quantile per
  (season, daytype, hour) is the SOTA reference approach
- Hildmann 2013, "Quality Criteria for HPFC" — calibration-by-construction
  is preferred over parametric bandwidth assumptions

Migration from v1 (multiplicative ratios + HORIZON_WIDENING)
------------------------------------------------------------
- `Uncertainty.fit()` / `compute()` signatures unchanged.
- `boot_stats_` value schema changed:
    v1: {"p10", "p50", "p90"}  multiplicative ratios
    v2: {"q10_res", "q90_res"} additive residuals (€/MWh)
- `save()` / `load()` parquet schema changed (q10_res/q90_res columns).
  Old v1 parquets must be regenerated by re-running `.fit()`.
- `HORIZON_WIDENING` module constant removed.
- `n_boot` / `seed` constructor args kept for API compat; ignored
  (empirical quantiles are exact estimators, no bootstrap needed).
"""

from __future__ import annotations

import logging
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

MIN_CELL_OBS = 20  # min obs to estimate q10/q90 reliably (binomial variance)
NOMINAL_IC = 0.80  # IC80 by construction
NOMINAL_TAIL = (1.0 - NOMINAL_IC) / 2.0  # 0.10 each side
FALLBACK_Q10_RES = -20.0  # €/MWh, conservative if cell too sparse
FALLBACK_Q90_RES = 20.0


class Uncertainty:
    """
    Empirical residual quantile prediction intervals for PFC IC80.

    Method (per cell = (saison, type_jour, heure_hce)):
        residuals = epex_price - cell_mean
        q10_res, q90_res = empirical 10/90 percentiles of residuals

    Compute (per timestamp t):
        p10(t) = pfc.price_shape(t) + q10_res[cell(t)]
        p90(t) = pfc.price_shape(t) + q90_res[cell(t)]

    Attributes
    ----------
    boot_stats_ : dict[(saison, type_jour, heure, quart)] -> dict
        Maps each (saison, type_jour, heure, quart) cell to a dict with
        keys 'q10_res' and 'q90_res' (additive residuals in €/MWh).
        All 4 quarters within an hour share the same residual quantiles
        (broadcast from hourly cells, since EPEX is hourly-resolution).
    """

    def __init__(self, n_boot: int = 0, seed: int = 42) -> None:
        self.n_boot = n_boot
        self.seed = seed
        self.boot_stats_: dict[tuple, dict] = {}

    def fit(
        self, epex_df: pd.DataFrame, calendar_df: pd.DataFrame
    ) -> "Uncertainty":
        """
        Calibrate empirical residual quantiles per (saison, type_jour, heure) cell.

        Args
        ----
        epex_df    : DataFrame with column 'price_eur_mwh', tz-aware UTC index
        calendar_df: enrichment with ['saison', 'type_jour', 'heure_hce', 'quart']

        Returns
        -------
        self
        """
        df = epex_df[["price_eur_mwh"]].join(
            calendar_df[["saison", "type_jour", "heure_hce", "quart"]]
        ).dropna()

        groups = df.groupby(["saison", "type_jour", "heure_hce"])
        logger.info(
            "Empirical residual quantile fit : %d hourly cells", len(groups)
        )

        hourly_stats: dict[tuple, dict] = {}
        n_fallback = 0
        for (saison, type_jour, h), grp in groups:
            if len(grp) < MIN_CELL_OBS:
                hourly_stats[(saison, type_jour, h)] = {
                    "q10_res": FALLBACK_Q10_RES,
                    "q90_res": FALLBACK_Q90_RES,
                }
                n_fallback += 1
                continue

            prices = grp["price_eur_mwh"].values
            residuals = prices - float(np.mean(prices))  # additive €/MWh
            q10_res = float(np.percentile(residuals, 100.0 * NOMINAL_TAIL))
            q90_res = float(np.percentile(residuals, 100.0 * (1.0 - NOMINAL_TAIL)))
            hourly_stats[(saison, type_jour, h)] = {
                "q10_res": q10_res,
                "q90_res": q90_res,
            }

        # Broadcast hourly → (h, quart) — EPEX is hourly-resolution, all 4
        # quarts of an hour share the same uncertainty.
        for (saison, type_jour, h), stats in hourly_stats.items():
            for q in range(1, 5):
                self.boot_stats_[(saison, type_jour, h, q)] = stats

        logger.info(
            "Residual quantile fit done : %d hourly cells → %d quart cells "
            "(%d fallback at MIN_CELL_OBS=%d)",
            len(hourly_stats),
            len(self.boot_stats_),
            n_fallback,
            MIN_CELL_OBS,
        )
        return self

    def compute(
        self,
        pfc_df: pd.DataFrame,
        calendar_df: pd.DataFrame,
        reference_date: pd.Timestamp | None = None,
    ) -> pd.DataFrame:
        """
        Compute p10 / p90 for each timestamp of pfc_df.

        Args
        ----
        pfc_df         : DataFrame with column 'price_shape', tz-aware UTC index
        calendar_df    : enrichment with ['saison', 'type_jour', 'heure_hce', 'quart']
        reference_date : unused in v2 (kept for API compat — horizon widening
                         is no longer applied; see module docstring)

        Returns
        -------
        DataFrame with columns ['p10', 'p90'] aligned on pfc_df.index
        """
        n = len(pfc_df)
        prices = pfc_df["price_shape"].values

        saisons = calendar_df["saison"].values
        types_jour = calendar_df["type_jour"].values
        heures = calendar_df["heure_hce"].astype(int).values
        quarts = calendar_df["quart"].astype(int).values

        q10_arr = np.full(n, FALLBACK_Q10_RES)
        q90_arr = np.full(n, FALLBACK_Q90_RES)

        # Vectorized cell lookup
        key_groups: dict[tuple, list[int]] = defaultdict(list)
        for i in range(n):
            key_groups[(saisons[i], types_jour[i], heures[i], quarts[i])].append(i)
        for key, indices in key_groups.items():
            if key in self.boot_stats_:
                s = self.boot_stats_[key]
                idx_arr = np.array(indices)
                q10_arr[idx_arr] = s["q10_res"]
                q90_arr[idx_arr] = s["q90_res"]

        # Additive residual quantiles (€/MWh)
        p10_out = prices + q10_arr
        p90_out = prices + q90_arr

        return pd.DataFrame(
            {"p10": p10_out, "p90": p90_out}, index=pfc_df.index
        )

    def save(self, path: str | Path) -> None:
        """Persist boot_stats_ (v2 schema: q10_res, q90_res columns)."""
        records = []
        for (saison, tj, h, q), stats in self.boot_stats_.items():
            records.append(
                {
                    "saison": saison,
                    "type_jour": tj,
                    "heure": h,
                    "quart": q,
                    "q10_res": stats["q10_res"],
                    "q90_res": stats["q90_res"],
                }
            )
        pd.DataFrame(records).to_parquet(path, index=False)
        logger.info("Uncertainty (v2 residual) saved : %s", path)

    @classmethod
    def load(cls, path: str | Path) -> "Uncertainty":
        """Load boot_stats_ from a v2 parquet (q10_res, q90_res columns)."""
        df = pd.read_parquet(path)
        if "q10_res" not in df.columns or "q90_res" not in df.columns:
            raise ValueError(
                f"Uncertainty.load: parquet at {path} is not v2 schema "
                f"(missing q10_res/q90_res). Re-fit and save."
            )
        obj = cls()
        for _, row in df.iterrows():
            key = (
                row["saison"],
                row["type_jour"],
                int(row["heure"]),
                int(row["quart"]),
            )
            obj.boot_stats_[key] = {
                "q10_res": float(row["q10_res"]),
                "q90_res": float(row["q90_res"]),
            }
        return obj
