"""
test_shape_hourly_bowl.py
--------------------------
Isolated test module for Phase 5bis-B math-change tests (D-A4-2, CONTEXT.md).

SCOPE
-----
This plan delivers 2 of 7 tests planned for Phase 5bis-B:
  - test_hydro_kernel_uses_per_timestamp_climatological_target (D-A4-3, Plan 05C-01)
  - test_flag_off_bit_for_bit_baseline                         (D-A4-8, Plan 05C-01)

Plans 05C-02 and 05C-03 will append:
  - test_split_level_anomaly_invariant       (D-A4-4, Plan 05C-02)
  - test_f_H_amplitude_preserved_at_M30     (D-A4-6, Plan 05C-02)
  - test_factors_ptp_deepens_under_flag      (D-A4-5, Plan 05C-03)
  - test_seasonal_solar_winter_evening_delta (D-A4-7, Plan 05C-03)
  - test_flag_on_bowl_baseline               (D-A4-9, Plan 05C-03)

NO-OP CONTRACT (from 5bis-A REVIEWS.md §1 tolerance addendum)
--------------------------------------------------------------
flag=OFF baseline test (D-A4-8 / SC #4) uses:
    pandas.testing.assert_frame_equal(
        build_pfc(flag=False), baseline,
        check_exact=False, atol=1e-12, rtol=0
    )
plus identical columns, dtypes, index, and sort order (parquet schema preserved).
This confirms that the Lever 1 kernel refactor preserves the flag=OFF path exactly.

FIXTURE-REAL GAP (RESEARCH Pitfall 5)
--------------------------------------
Tests D-A4-3, D-A4-8 in this file use synthetic bowl_seed42 fixture.

Pass = math correcte (condition nécessaire for SC #1..#4).
Phase 10 validates on HFC OMPEX RÉEL = condition suffisante (data fit).
Failure here = math broken (ship-blocker immédiat).
Pass here + failure Phase 10 = fixture-real gap (informe future fixture design,
NOT a rollback of 5bis-B).

THRESHOLD CONSTANTS (M2 cross-AI review fix, REVIEWS.md consensus #3)
----------------------------------------------------------------------
SC1_PTP_THRESHOLD and SC3_M30_AMPLITUDE_THRESHOLD are loaded from the committed
immutable calibration report tests/fixtures/_bowl_calibration_report.json.

To refresh thresholds after changing the fixture or model:
    python scripts/calibrate_bowl_thresholds.py
Then re-commit both the script and the updated JSON.

Plan 05C-02 Task 3 replaced SC3_M30_AMPLITUDE_THRESHOLD_PLACEHOLDER with the calibrated
SC3_M30_AMPLITUDE_THRESHOLD key (value=0.50, plancher; ptp_on_m30=0.356, ratio=1.87).
Plan 05C-03 Task 3 re-runs calibration with all 3 levers active and overwrites
SC1_PTP_THRESHOLD with the final 3-lever ratio.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import numpy.testing as npt
import pandas as pd
import pytest
from pandas.testing import assert_frame_equal

from pfc_shaping.data.calendar_ch import enrich_15min_index
from pfc_shaping.lt.model.assembler import PFCAssembler
from pfc_shaping.lt.model.shape_hourly import ShapeHourly, _split_level_anomaly
from pfc_shaping.lt.model.shape_intraday import ShapeIntraday

# ---------------------------------------------------------------------------
# Reusable entry points from committed fixtures
# ---------------------------------------------------------------------------
from tests.fixtures._generate_baseline import build_pfc as build_baseline_pfc
from tests.fixtures._generate_bowl_fixture import build_bowl_fixture

# ---------------------------------------------------------------------------
# Module-level path constants
# ---------------------------------------------------------------------------
_FIXTURE_DIR = Path(__file__).parent / "fixtures"
_BASELINE_5BISA = _FIXTURE_DIR / "baseline_pfc_seed42.parquet"
_BASELINE_BOWL = _FIXTURE_DIR / "baseline_pfc_seed42_bowl.parquet"  # generated by Plan 05C-03

# ---------------------------------------------------------------------------
# Threshold constants — M2 cross-AI review fix (REVIEWS.md consensus #3)
# Loaded from committed _bowl_calibration_report.json (NOT in-comment values).
# ---------------------------------------------------------------------------
_CALIBRATION_REPORT_PATH = _FIXTURE_DIR / "_bowl_calibration_report.json"
_calibration_report = json.loads(_CALIBRATION_REPORT_PATH.read_text())

# SC1_PTP_THRESHOLD: minimum ratio np.ptp(factors_on) / np.ptp(factors_off) required
# to pass SC #1 (Plan 05C-01 Lever-1-only gain). Plan 05C-03 Task 3 re-runs calibration
# with all 3 levers; the threshold value in the JSON will be updated then.
# To refresh: python scripts/calibrate_bowl_thresholds.py
SC1_PTP_THRESHOLD: float = _calibration_report["thresholds_emitted"]["SC1_PTP_THRESHOLD"]

# SC3_M30_AMPLITUDE_THRESHOLD: minimum ptp(f_H) at M+30 to prove Lever 2 preserves bowl
# at far horizon. Calibrated by Plan 05C-02 Task 3 (Wave 0 measure-then-assert, M2 fix).
# Value: max(ptp_on - 0.20, ptp_off * 1.50, 0.50) = 0.50 (plancher, fixture covers Jan-Mar only;
# ptp_on_m30 = 0.356, ptp_off_m30 = 0.190, ratio = 1.87 confirming Lever 2 amplifies M+30 bowl).
# Plan 05C-03 Task 3 will re-run calibration with all 3 levers active and overwrite this value.
SC3_M30_AMPLITUDE_THRESHOLD: float = _calibration_report["thresholds_emitted"][
    "SC3_M30_AMPLITUDE_THRESHOLD"  # Plan 05C-02 Task 3: calibrated (replaces PLACEHOLDER key)
]


# ---------------------------------------------------------------------------
# Module-level fixture (built once per test session)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def bowl_data():
    """Build the deterministic bowl fixture once per module (seed=42).

    Returns:
        dict with keys:
          - epex_df: 15-min EPEX DataFrame with duck curve
          - hydro_df: weekly Swiss hydro reservoir fill
          - cal: calendar enrichment for epex_df.index
    """
    epex_df, hydro_df = build_bowl_fixture(seed=42)
    cal = enrich_15min_index(epex_df.index, country="CH")
    return {"epex_df": epex_df, "hydro_df": hydro_df, "cal": cal}


# ---------------------------------------------------------------------------
# Test 1 — D-A4-3 (Lever 1 kernel verification)
# ---------------------------------------------------------------------------

def test_hydro_kernel_uses_per_timestamp_climatological_target(bowl_data):
    """Verify that _apply_hydro_analogue_weights uses per-timestamp clim target when flag=ON.

    Decision reference: D-A4-3 (CONTEXT.md §Test design Area 4).
    Implementation: D-A1-1 — kernel target = get_climatological_fill(woy(t)) per sample.
    Safety: uses Option A (private debug attribute _last_clim_target_) per plan Task 5.

    RESEARCH §Implementation Pitfalls 1: get_climatological_fill() is used internally
    (nearest-neighbor safe), not direct dict access.

    Asserts:
    - flag=ON: _last_clim_target_ is a NumPy array; each entry equals
      get_climatological_fill(woy(df.index[i])) for the timestamps consumed by the kernel.
    - flag=OFF: _last_clim_target_ is a scalar float equal to the legacy current_fill
      (float(hydro_df["fill_pct"].iloc[-1] / 100.0)).
    """
    epex_df = bowl_data["epex_df"]
    hydro_df = bowl_data["hydro_df"]
    cal = bowl_data["cal"]

    # Fit both models
    sh_on = ShapeHourly(use_seasonal_hourly=True).fit(epex_df, cal, hydro_df)
    sh_off = ShapeHourly(use_seasonal_hourly=False).fit(epex_df, cal, hydro_df)

    # --- flag=ON verification ---
    assert hasattr(sh_on, "_last_clim_target_"), (
        "_last_clim_target_ debug attribute missing from sh_on — "
        "check Task 2 Edit B implementation"
    )
    clim_target_on = sh_on._last_clim_target_
    assert isinstance(clim_target_on, np.ndarray), (
        f"flag=ON: _last_clim_target_ should be ndarray, got {type(clim_target_on)}"
    )
    # The kernel operates on df.index (after fill_at_date alignment and valid_mask check).
    # We verify that the clim_target array has the same length as epex_df (the full
    # df fed to the kernel — alignment drops NaN rows, but for the fixture the fill
    # covers the full range so all rows should be valid).
    assert len(clim_target_on) == len(epex_df), (
        f"flag=ON: _last_clim_target_ length {len(clim_target_on)} != "
        f"epex_df length {len(epex_df)}"
    )

    # Independently compute expected clim targets from the fitted model
    if hasattr(epex_df.index, "isocalendar"):
        woy_arr = epex_df.index.isocalendar().week.values
    else:
        woy_arr = epex_df.index.to_series().dt.isocalendar().week.values

    expected_clim_target = np.array(
        [sh_on.get_climatological_fill(int(w)) for w in woy_arr], dtype=float
    )

    np.testing.assert_allclose(
        clim_target_on,
        expected_clim_target,
        atol=1e-12,
        rtol=0,
        err_msg=(
            "flag=ON: _last_clim_target_ does not match get_climatological_fill(woy(t)) "
            "for each timestamp. Kernel is NOT using per-timestamp clim target (D-A1-1)."
        ),
    )

    # --- flag=OFF verification (legacy scalar current_fill) ---
    assert hasattr(sh_off, "_last_clim_target_"), (
        "_last_clim_target_ debug attribute missing from sh_off"
    )
    clim_target_off = sh_off._last_clim_target_
    assert isinstance(clim_target_off, float), (
        f"flag=OFF: _last_clim_target_ should be scalar float, got {type(clim_target_off)}"
    )

    # Legacy current_fill = fill.iloc[-1] after normalize-to-[0,1] step
    fill_raw = hydro_df["fill_pct"].dropna()
    if fill_raw.max() > 1.5:
        fill_norm = fill_raw / 100.0
    else:
        fill_norm = fill_raw
    expected_current_fill = float(fill_norm.iloc[-1])

    np.testing.assert_allclose(
        clim_target_off,
        expected_current_fill,
        atol=1e-12,
        rtol=0,
        err_msg=(
            f"flag=OFF: _last_clim_target_={clim_target_off:.6f} != "
            f"expected current_fill={expected_current_fill:.6f}. "
            "Legacy kernel must use the scalar current_fill (D-A1-2)."
        ),
    )


# ---------------------------------------------------------------------------
# Test 2 — D-A4-8 (SC #4: flag=OFF baseline bit-pour-bit)
# ---------------------------------------------------------------------------

def test_flag_off_bit_for_bit_baseline():
    """SC #4: flag=OFF baseline preserved bit-pour-bit after Lever 1 kernel refactor.

    Decision reference: D-A4-8 (CONTEXT.md §Test design Area 4).
    Extends 5bis-A test_baseline_regression[False] to the 5bis-B refactored kernel
    surface — the no-op contract is preserved by the flag=OFF branch in
    _apply_hydro_analogue_weights (D-A1-2).

    Tolerance contract: 5bis-A REVIEWS.md §1 addendum — NOT byte equivalence:
        assert_frame_equal(check_exact=False, atol=1e-12, rtol=0)
    plus identical columns, dtypes, index, and sort order.

    CI-drift fallback policy (from 5bis-A Plan 05B-05 Task 3 contract):
        Default atol=1e-12, rtol=0. If pandas/pyarrow patch-level drift breaks this
        in CI, fallback to atol=1e-10 is permitted with an inline comment.
    """
    df_off = build_baseline_pfc(seed=42, flag=False)
    baseline = pd.read_parquet(_BASELINE_5BISA)

    # Strict schema identity (columns, dtypes, index)
    assert list(df_off.columns) == list(baseline.columns), (
        f"Column mismatch: got {list(df_off.columns)}, expected {list(baseline.columns)}"
    )
    assert df_off.dtypes.to_dict() == baseline.dtypes.to_dict(), (
        f"Dtype mismatch: {df_off.dtypes.to_dict()} vs {baseline.dtypes.to_dict()}"
    )
    assert df_off.index.equals(baseline.index), (
        "Index mismatch — sort order or timestamps differ"
    )

    # Numerical equality at the 5bis-A REVIEWS tolerance contract.
    # Parquet does NOT preserve DatetimeIndex.freq — the fresh DataFrame has
    # freq=<15 * Minutes> while the loaded baseline has freq=None. Reset freq
    # on the fresh frame before comparing so assert_frame_equal does not fail on freq.
    # (Same workaround as test_baseline_regression in test_shape_hourly_infra.py.)
    df_cmp = df_off.copy()
    df_cmp.index.freq = None
    assert_frame_equal(
        df_cmp,
        baseline,
        check_exact=False,
        atol=1e-12,
        rtol=0,
    )


# ---------------------------------------------------------------------------
# Test 3 — D-A4-4 (Lever 2 split invariant, Plan 05C-02)
# ---------------------------------------------------------------------------

def test_split_level_anomaly_invariant():
    """Direct verification of the two D-A2-2 invariants of _split_level_anomaly.

    Decision references: D-A4-4 (CONTEXT.md §Test design Area 4), D-A2-2 (split math).
    Plan: 05C-02 Task 4.

    Tests the helper directly on synthetic f_H arrays, independent of assembler.build().
    This isolates the math from the build pipeline: if this test fails, the bug is in
    the helper itself; if test_f_H_amplitude_preserved_at_M30 fails but this passes,
    the bug is in the assembler integration.

    Asserts:
    1. ulp-exact sum: numpy.allclose(level + anomaly, f_H, atol=1e-15, rtol=0)
    2. zero-mean per cell: abs(anomaly.groupby(cell).mean()).max() < 1e-12
    3. index alignment: level.index / anomaly.index == f_H_series.index
    4. names: level.name == "level", anomaly.name == "anomaly"
    """
    # Synthetic f_H: two cells (Hiver/Ouvrable x48, Ete/Samedi x48), seed=123
    idx = pd.date_range("2027-01-01", periods=96, freq="15min", tz="UTC")
    f_H_series = pd.Series(
        np.random.default_rng(123).normal(1.0, 0.15, 96),
        index=idx,
        name="f_H",
    )
    cal_df = pd.DataFrame(
        {
            "saison": ["Hiver"] * 48 + ["Ete"] * 48,
            "type_jour": ["Ouvrable"] * 96,
        },
        index=idx,
    )

    level, anomaly = _split_level_anomaly(f_H_series, cal_df)

    # 1. ulp-exact sum (D-A2-2 invariant 1: level + anomaly == f_H)
    npt.assert_allclose(
        level.values + anomaly.values,
        f_H_series.values,
        atol=1e-15,
        rtol=0,
        err_msg="D-A2-2 violated: level + anomaly != f_H at ulp precision",
    )

    # 2. zero-mean per cell (D-A2-2 invariant 2: mean(anomaly | cell) == 0)
    anom_df = anomaly.to_frame("anomaly").join(cal_df[["saison", "type_jour"]])
    cell_anom_means = anom_df.groupby(["saison", "type_jour"])["anomaly"].mean()
    max_cell_drift = float(abs(cell_anom_means).max())
    assert max_cell_drift < 1e-12, (
        f"D-A2-2 violated: per-cell mean of anomaly = {max_cell_drift:.2e} (expected < 1e-12). "
        "Zero-mean invariant failed."
    )

    # 3. index alignment
    assert level.index.equals(f_H_series.index), "level.index != f_H_series.index"
    assert anomaly.index.equals(f_H_series.index), "anomaly.index != f_H_series.index"

    # 4. names
    assert level.name == "level", f"level.name = {level.name!r} (expected 'level')"
    assert anomaly.name == "anomaly", f"anomaly.name = {anomaly.name!r} (expected 'anomaly')"


# ---------------------------------------------------------------------------
# Test 4 — D-A4-6 / SC #3 (M+30 amplitude preserved, Plan 05C-02)
# ---------------------------------------------------------------------------

def test_f_H_amplitude_preserved_at_M30(bowl_data):
    """SC #3: Lever 2 preserves f_H bowl amplitude at M+30 horizon.

    Decision references: D-A4-6 (CONTEXT.md §Test design Area 4), SC #3 (ROADMAP).
    Plan: 05C-02 Task 4.

    RESEARCH §Lever 2 dry-run (05C-RESEARCH.md):
        Legacy M+30 ptp(f_H): ~0.516 (full damping, sf=0.52 at 30 months)
        Split M+30 ptp(f_H): ~0.992 (anomaly survives, level ≈ 1.0 by SHP-03)
        Expected gain ratio: ~1.92

    Measured on bowl_seed42 fixture (Jan-Mar only, Ete cells fall back to Ouvrable):
        ptp_off_m30 = 0.1902, ptp_on_m30 = 0.3558, ratio = 1.87
        SC3_M30_AMPLITUDE_THRESHOLD = 0.50 (plancher; calibrated by Task 3 Wave 0)

    The test asserts ptp(f_H) at ~M+30 under flag=ON > SC3_M30_AMPLITUDE_THRESHOLD.
    This is SC #3: Lever 2 quantitatively proves the duck curve survives at far horizon.

    FIXTURE-REAL GAP: bowl_seed42 covers Jan-Mar; Ete cells fall back to Ouvrable at the
    June 2029 build date. Absolute ptp_on_m30 = 0.356 vs theoretical 0.99 (full-year fixture).
    The test validates correctness of the split math (ratio 1.87 ≈ theoretical 1.92 is accurate).
    Phase 10 validates on HFC OMPEX RÉEL (condition suffisante).
    """
    epex_df = bowl_data["epex_df"]
    hydro_df = bowl_data["hydro_df"]
    cal_3yr = bowl_data["cal"]

    # Fit ShapeHourly with flag=ON (Lever 1 + Lever 2)
    sh_on = ShapeHourly(use_seasonal_hourly=True).fit(epex_df, cal_3yr, hydro_df)

    # Fit minimal ShapeIntraday (mirror _generate_baseline.py pattern)
    si = ShapeIntraday().fit(epex_df, entso_df=None, calendar_df=cal_3yr)

    # Build PFC at far horizon ~M+30 (start_date=2029-06-01, reference=2027-01-01)
    assembler = PFCAssembler(
        shape_hourly=sh_on,
        shape_intraday=si,
        uncertainty=None,
        water_value=None,
        cascader=None,
        calibrator=None,
    )
    df_pfc = assembler.build(
        base_prices={"2029": 80.0},
        start_date="2029-06-01",
        horizon_days=31,
        reference_date=pd.Timestamp("2027-01-01", tz="UTC"),
        country="CH",
    )

    ptp_observed = float(np.ptp(df_pfc["f_H"]))
    assert ptp_observed > SC3_M30_AMPLITUDE_THRESHOLD, (
        f"SC #3 FAILED: np.ptp(f_H) at ~M+30 = {ptp_observed:.4f} < "
        f"SC3_M30_AMPLITUDE_THRESHOLD = {SC3_M30_AMPLITUDE_THRESHOLD:.4f}. "
        "Lever 2 is NOT preserving bowl amplitude at far horizon. "
        "If the threshold seems stale, re-run: python scripts/calibrate_bowl_thresholds.py"
    )
