"""
test_shape_hourly_bowl.py
--------------------------
Isolated test module for Phase 5bis-B math-change tests (D-A4-2, CONTEXT.md).

SCOPE
-----
This plan delivers 2 of 7 tests planned for Phase 5bis-B:
  - test_hydro_kernel_uses_per_timestamp_climatological_target (D-A4-3, Plan 05C-01)
  - test_flag_off_bit_for_bit_baseline                         (D-A4-8, Plan 05C-01)

Plans 05C-02 and 05C-03 will append:
  - test_split_level_anomaly_invariant       (D-A4-4, Plan 05C-02)
  - test_f_H_amplitude_preserved_at_M30     (D-A4-6, Plan 05C-02)
  - test_factors_ptp_deepens_under_flag      (D-A4-5, Plan 05C-03)
  - test_seasonal_solar_winter_evening_delta (D-A4-7, Plan 05C-03)
  - test_flag_on_bowl_baseline               (D-A4-9, Plan 05C-03)

NO-OP CONTRACT (from 5bis-A REVIEWS.md §1 tolerance addendum)
--------------------------------------------------------------
flag=OFF baseline test (D-A4-8 / SC #4) uses:
    pandas.testing.assert_frame_equal(
        build_pfc(flag=False), baseline,
        check_exact=False, atol=1e-12, rtol=0
    )
plus identical columns, dtypes, index, and sort order (parquet schema preserved).
This confirms that the Lever 1 kernel refactor preserves the flag=OFF path exactly.

FIXTURE-REAL GAP (RESEARCH Pitfall 5)
--------------------------------------
Tests D-A4-3, D-A4-8 in this file use synthetic bowl_seed42 fixture.

Pass = math correcte (condition nécessaire for SC #1..#4).
Phase 10 validates on HFC OMPEX RÉEL = condition suffisante (data fit).
Failure here = math broken (ship-blocker immédiat).
Pass here + failure Phase 10 = fixture-real gap (informe future fixture design,
NOT a rollback of 5bis-B).

THRESHOLD CONSTANTS (M2 cross-AI review fix, REVIEWS.md consensus #3)
----------------------------------------------------------------------
SC1_PTP_THRESHOLD and SC3_M30_AMPLITUDE_THRESHOLD are loaded from the committed
immutable calibration report tests/fixtures/_bowl_calibration_report.json.

To refresh thresholds after changing the fixture or model:
    python scripts/calibrate_bowl_thresholds.py
Then re-commit both the script and the updated JSON.

Plan 05C-02 Task 3 updates SC3_M30_AMPLITUDE_THRESHOLD_PLACEHOLDER in the JSON.
Plan 05C-03 Task 3 re-runs calibration with all 3 levers active and overwrites
SC1_PTP_THRESHOLD with the final 3-lever ratio.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from pandas.testing import assert_frame_equal

from pfc_shaping.data.calendar_ch import enrich_15min_index
from pfc_shaping.lt.model.shape_hourly import ShapeHourly

# ---------------------------------------------------------------------------
# Reusable entry points from committed fixtures
# ---------------------------------------------------------------------------
from tests.fixtures._generate_baseline import build_pfc as build_baseline_pfc
from tests.fixtures._generate_bowl_fixture import build_bowl_fixture

# ---------------------------------------------------------------------------
# Module-level path constants
# ---------------------------------------------------------------------------
_FIXTURE_DIR = Path(__file__).parent / "fixtures"
_BASELINE_5BISA = _FIXTURE_DIR / "baseline_pfc_seed42.parquet"
_BASELINE_BOWL = _FIXTURE_DIR / "baseline_pfc_seed42_bowl.parquet"  # generated by Plan 05C-03

# ---------------------------------------------------------------------------
# Threshold constants — M2 cross-AI review fix (REVIEWS.md consensus #3)
# Loaded from committed _bowl_calibration_report.json (NOT in-comment values).
# ---------------------------------------------------------------------------
_CALIBRATION_REPORT_PATH = _FIXTURE_DIR / "_bowl_calibration_report.json"
_calibration_report = json.loads(_CALIBRATION_REPORT_PATH.read_text())

# SC1_PTP_THRESHOLD: minimum ratio np.ptp(factors_on) / np.ptp(factors_off) required
# to pass SC #1 (Plan 05C-01 Lever-1-only gain). Plan 05C-03 Task 3 re-runs calibration
# with all 3 levers; the threshold value in the JSON will be updated then.
# To refresh: python scripts/calibrate_bowl_thresholds.py
SC1_PTP_THRESHOLD: float = _calibration_report["thresholds_emitted"]["SC1_PTP_THRESHOLD"]

# SC3_M30_AMPLITUDE_THRESHOLD: minimum ptp(f_H) at M+30 to prove Lever 2 preserves bowl
# at far horizon. PLACEHOLDER value 0.50 (see 05C-RESEARCH.md §M+30 amplitude threshold).
# Plan 05C-02 Task 3 updates the JSON's SC3_M30_AMPLITUDE_THRESHOLD_PLACEHOLDER key.
SC3_M30_AMPLITUDE_THRESHOLD: float = _calibration_report["thresholds_emitted"][
    "SC3_M30_AMPLITUDE_THRESHOLD_PLACEHOLDER"
]


# ---------------------------------------------------------------------------
# Module-level fixture (built once per test session)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def bowl_data():
    """Build the deterministic bowl fixture once per module (seed=42).

    Returns:
        dict with keys:
          - epex_df: 15-min EPEX DataFrame with duck curve
          - hydro_df: weekly Swiss hydro reservoir fill
          - cal: calendar enrichment for epex_df.index
    """
    epex_df, hydro_df = build_bowl_fixture(seed=42)
    cal = enrich_15min_index(epex_df.index, country="CH")
    return {"epex_df": epex_df, "hydro_df": hydro_df, "cal": cal}


# ---------------------------------------------------------------------------
# Test 1 — D-A4-3 (Lever 1 kernel verification)
# ---------------------------------------------------------------------------

def test_hydro_kernel_uses_per_timestamp_climatological_target(bowl_data):
    """Verify that _apply_hydro_analogue_weights uses per-timestamp clim target when flag=ON.

    Decision reference: D-A4-3 (CONTEXT.md §Test design Area 4).
    Implementation: D-A1-1 — kernel target = get_climatological_fill(woy(t)) per sample.
    Safety: uses Option A (private debug attribute _last_clim_target_) per plan Task 5.

    RESEARCH §Implementation Pitfalls 1: get_climatological_fill() is used internally
    (nearest-neighbor safe), not direct dict access.

    Asserts:
    - flag=ON: _last_clim_target_ is a NumPy array; each entry equals
      get_climatological_fill(woy(df.index[i])) for the timestamps consumed by the kernel.
    - flag=OFF: _last_clim_target_ is a scalar float equal to the legacy current_fill
      (float(hydro_df["fill_pct"].iloc[-1] / 100.0)).
    """
    epex_df = bowl_data["epex_df"]
    hydro_df = bowl_data["hydro_df"]
    cal = bowl_data["cal"]

    # Fit both models
    sh_on = ShapeHourly(use_seasonal_hourly=True).fit(epex_df, cal, hydro_df)
    sh_off = ShapeHourly(use_seasonal_hourly=False).fit(epex_df, cal, hydro_df)

    # --- flag=ON verification ---
    assert hasattr(sh_on, "_last_clim_target_"), (
        "_last_clim_target_ debug attribute missing from sh_on — "
        "check Task 2 Edit B implementation"
    )
    clim_target_on = sh_on._last_clim_target_
    assert isinstance(clim_target_on, np.ndarray), (
        f"flag=ON: _last_clim_target_ should be ndarray, got {type(clim_target_on)}"
    )
    # The kernel operates on df.index (after fill_at_date alignment and valid_mask check).
    # We verify that the clim_target array has the same length as epex_df (the full
    # df fed to the kernel — alignment drops NaN rows, but for the fixture the fill
    # covers the full range so all rows should be valid).
    assert len(clim_target_on) == len(epex_df), (
        f"flag=ON: _last_clim_target_ length {len(clim_target_on)} != "
        f"epex_df length {len(epex_df)}"
    )

    # Independently compute expected clim targets from the fitted model
    if hasattr(epex_df.index, "isocalendar"):
        woy_arr = epex_df.index.isocalendar().week.values
    else:
        woy_arr = epex_df.index.to_series().dt.isocalendar().week.values

    expected_clim_target = np.array(
        [sh_on.get_climatological_fill(int(w)) for w in woy_arr], dtype=float
    )

    np.testing.assert_allclose(
        clim_target_on,
        expected_clim_target,
        atol=1e-12,
        rtol=0,
        err_msg=(
            "flag=ON: _last_clim_target_ does not match get_climatological_fill(woy(t)) "
            "for each timestamp. Kernel is NOT using per-timestamp clim target (D-A1-1)."
        ),
    )

    # --- flag=OFF verification (legacy scalar current_fill) ---
    assert hasattr(sh_off, "_last_clim_target_"), (
        "_last_clim_target_ debug attribute missing from sh_off"
    )
    clim_target_off = sh_off._last_clim_target_
    assert isinstance(clim_target_off, float), (
        f"flag=OFF: _last_clim_target_ should be scalar float, got {type(clim_target_off)}"
    )

    # Legacy current_fill = fill.iloc[-1] after normalize-to-[0,1] step
    fill_raw = hydro_df["fill_pct"].dropna()
    if fill_raw.max() > 1.5:
        fill_norm = fill_raw / 100.0
    else:
        fill_norm = fill_raw
    expected_current_fill = float(fill_norm.iloc[-1])

    np.testing.assert_allclose(
        clim_target_off,
        expected_current_fill,
        atol=1e-12,
        rtol=0,
        err_msg=(
            f"flag=OFF: _last_clim_target_={clim_target_off:.6f} != "
            f"expected current_fill={expected_current_fill:.6f}. "
            "Legacy kernel must use the scalar current_fill (D-A1-2)."
        ),
    )


# ---------------------------------------------------------------------------
# Test 2 — D-A4-8 (SC #4: flag=OFF baseline bit-pour-bit)
# ---------------------------------------------------------------------------

def test_flag_off_bit_for_bit_baseline():
    """SC #4: flag=OFF baseline preserved bit-pour-bit after Lever 1 kernel refactor.

    Decision reference: D-A4-8 (CONTEXT.md §Test design Area 4).
    Extends 5bis-A test_baseline_regression[False] to the 5bis-B refactored kernel
    surface — the no-op contract is preserved by the flag=OFF branch in
    _apply_hydro_analogue_weights (D-A1-2).

    Tolerance contract: 5bis-A REVIEWS.md §1 addendum — NOT byte equivalence:
        assert_frame_equal(check_exact=False, atol=1e-12, rtol=0)
    plus identical columns, dtypes, index, and sort order.

    CI-drift fallback policy (from 5bis-A Plan 05B-05 Task 3 contract):
        Default atol=1e-12, rtol=0. If pandas/pyarrow patch-level drift breaks this
        in CI, fallback to atol=1e-10 is permitted with an inline comment.
    """
    df_off = build_baseline_pfc(seed=42, flag=False)
    baseline = pd.read_parquet(_BASELINE_5BISA)

    # Strict schema identity (columns, dtypes, index)
    assert list(df_off.columns) == list(baseline.columns), (
        f"Column mismatch: got {list(df_off.columns)}, expected {list(baseline.columns)}"
    )
    assert df_off.dtypes.to_dict() == baseline.dtypes.to_dict(), (
        f"Dtype mismatch: {df_off.dtypes.to_dict()} vs {baseline.dtypes.to_dict()}"
    )
    assert df_off.index.equals(baseline.index), (
        "Index mismatch — sort order or timestamps differ"
    )

    # Numerical equality at the 5bis-A REVIEWS tolerance contract.
    # Parquet does NOT preserve DatetimeIndex.freq — the fresh DataFrame has
    # freq=<15 * Minutes> while the loaded baseline has freq=None. Reset freq
    # on the fresh frame before comparing so assert_frame_equal does not fail on freq.
    # (Same workaround as test_baseline_regression in test_shape_hourly_infra.py.)
    df_cmp = df_off.copy()
    df_cmp.index.freq = None
    assert_frame_equal(
        df_cmp,
        baseline,
        check_exact=False,
        atol=1e-12,
        rtol=0,
    )
