"""Stable process exit codes shared by governed LT command surfaces."""

EXIT_SUCCESS = 0
EXIT_USAGE = 2
EXIT_GOVERNANCE_PENDING = 30
EXIT_CAS_CONFLICT = 40
EXIT_TRANSITION_BUSY = 41
EXIT_INTEGRITY_FAILURE = 50
EXIT_PROJECTION_REPAIR_REQUIRED = 51
EXIT_INDETERMINATE = 52
